disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "everyone, meet fel1x"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "A blog about my life, my projects and my thoughts"

["params.author"]
name = "Felix Hoang"
headline = "cs student @ USF"
email = "xuanphuc.a1gv@gmail.com"
image = "logos/web-app-manifest-512x512.png"
links = [
  { email = "mailto:xuanphuc.a1gv@gmail.com" },
  { github = "https://github.com/phuchoang2603" },
  { linkedin = "https://linkedin.com/in/phuchoang2603" },
]
